# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
describe 'Signin' do
  before(:each) do
    @driver = Selenium::WebDriver.for :firefox
    @vars = {}
  end
  after(:each) do
    @driver.close()
  end
  it 'signin' do
    @driver.get('http://localhost:3000/')
    @driver.find_element(:link_text, 'New user').click
    @driver.find_element(:id, 'user_username').click
    @driver.find_element(:id, 'user_username').send_keys('user')
    @driver.find_element(:css, 'div:nth-child(3)').click
    @driver.find_element(:id, 'user_email').click
    @driver.find_element(:id, 'user_email').send_keys('email@gmail.com')
    @driver.find_element(:css, 'html').click
    @driver.find_element(:id, 'user_password').click
    @driver.find_element(:id, 'user_password').send_keys('password')
    @driver.find_element(:css, 'html').click
    @driver.find_element(:name, 'commit').click
    @driver.get('http://localhost:3000/')
    @driver.find_element(:id, 'email').click
    @driver.find_element(:id, 'email').send_keys('email@gmail.com')
    @driver.find_element(:css, 'body').click
    @driver.find_element(:id, 'password').click
    @driver.find_element(:id, 'password').send_keys('password')
    @driver.find_element(:name, 'commit').click
    @driver.find_element(:id, 'less_than_number').click
    @driver.find_element(:id, 'less_than_number').send_keys('10000')
    @driver.find_element(:name, 'commit').click
    expect(@driver.find_element(:css, 'tr:nth-child(21) > th:nth-child(2)').text).to eq('19')
    @driver.find_element(:link_text, 'To userlist').click
    @driver.find_element(:css, 'button').click
  end
end
